[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]

[db]
major_version = 15

[studio]
enabled = true

[analytics]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/**"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
enabled = true
policy = "per_worker"

[functions."assign-teacher"]
enabled = true
verify_jwt = false

[functions."create-checkout-session"]
enabled = true
verify_jwt = false

[functions."stripe-webhook"]
enabled = true
verify_jwt = false

[storage]
enabled = true
file_size_limit = "50MB"
